### ISSUE TITLE
Solution-Checker two robots carrying same shelf

### ISSUE THREAD

**Issue by jonasumland** [potassco/asprilo#26] opened 2019-04-12 10:46 UTC
The a-domain solution checker is not detecting the following case:
Instance:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Grid size X: 2
%Grid size Y: 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#program base.

%init
init(object(node, 2), value(at, (2, 1))).
init(object(node, 4), value(at, (2, 2))).
init(object(node, 3), value(at, (1, 2))).
init(object(node, 1), value(at, (1, 1))).
init(object(pickingStation,1), value(at,(1,1))).
init(object(robot,1), value(at,(1,2))).
init(object(robot,2), value(at,(2,1))).
init(object(shelf,1), value(at,(2,2))).
init(object(product,1),value(on,(1,1))).
init(object(order,1),value(pickingStation,1)).init(object(order,1),value(line,(1,1))).
```
![pickupDifferentRobot](https://user-images.githubusercontent.com/15263011/56031573-34f02200-5d20-11e9-9bc6-5612b6eda9a6.png)

Plan: 
```
occurs(object(robot,1),action(move,(1,0)),1).
occurs(object(robot,1),action(pickup,()),2).
occurs(object(robot,2),action(move,(0,1)),3).
occurs(object(robot,1),action(move,(-1,0)),3).
occurs(object(robot,2),action(pickup,()),4).
occurs(object(robot,1),action(move,(0,-1)),4).
occurs(object(robot,2),action(putdown,()),5).
occurs(object(robot,1),action(deliver,(1,1,1)),5).
```
no mistake is detected even though the same shelf is picked up twice. 
when you add the statement `#show holds(object(robot, R), value(carries, S), T): holds(object(robot, R), value(carries, S), T).`
You get 
```
holds(object(robot,1),value(carries,1),2) holds(object(robot,1),value(carries,1),3) holds(object(robot,1),value(carries,1),4) holds(object(robot,2),value(carries,1),4) holds(object(robot,1),value(carries,1),5)
```
At timestep 4 robot 1 and 2 are carrying the shelf 1.
There is missing a mechanism for updating the shelf positions after pickup and putdown.

**Comment by pobermei** [comment] 2019-04-15 14:05
Thanks for pointing this out! This was caused by a typo, fixed in d54a0e2.

**Closed as completed by pobermei** 2019-04-15 14:05 UTC
