### ISSUE TITLE
Generator: AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by dalyaki** [potassco/asprilo#35] opened 2020-05-28 17:05 UTC
The gen -h command runs, any attempt at generation yields the error.
Clingo and Generator installed through anaconda.
System:Windows 10

Console log:
Traceback (most recent call last):
  File "C:\Users\Dalya\anaconda3\envs\myenv\Scripts\gen-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Dalya\anaconda3\envs\myenv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\__main__.py", line 11, in main
  File "C:\Users\Dalya\anaconda3\envs\myenv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 74, in run
  File "C:\Users\Dalya\anaconda3\envs\myenv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 84, in _run_once
  File "C:\Users\Dalya\anaconda3\envs\myenv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 227, in _gen_basic
  File "C:\Users\Dalya\anaconda3\envs\myenv\lib\site-packages\generator-0.2.0-py3.6.egg\generator\generator.py", line 138, in generate
AttributeError: module 'signal' has no attribute 'SIGALRM'

**Comment by pobermei** [comment] 2020-06-04 21:28
This is a duplicate of https://github.com/potassco/asprilo/issues/33

**Closed as completed by pobermei** 2020-06-04 21:28 UTC
