### ISSUE TITLE
Generator error

### ISSUE THREAD

**Issue by salewsky** [potassco/asprilo#39] opened 2020-12-09 15:53 UTC
I got the following error message when using the asprilo generator:

Traceback (most recent call last):
  File "C:\Users\Adrian\anaconda3\Scripts\gen-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Adrian\anaconda3\lib\site-packages\generator-0.2.0-py3.6.egg\generator\__main__.py", line 11, in main
  File "C:\Users\Adrian\anaconda3\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 74, in run
  File "C:\Users\Adrian\anaconda3\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 84, in _run_once
  File "C:\Users\Adrian\anaconda3\lib\site-packages\generator-0.2.0-py3.6.egg\generator\control.py", line 227, in _gen_basic
  File "C:\Users\Adrian\anaconda3\lib\site-packages\generator-0.2.0-py3.6.egg\generator\generator.py", line 138, in generate
AttributeError: module 'signal' has no attribute 'SIGALRM'

I am using Windows 10 and anaconda 3 with a terminal. The generator version is 0.3.0. 
The command I used was: gen -x 5 -y 3
but I also tried different commands, including the ones provided as an example in the readme. The error message was always the same.

**Comment by tortinator** [comment] 2020-12-10 11:01
Hallo @pobermei , could you check this out? Cheers! @tortinator

**Comment by pobermei** [comment] 2020-12-10 11:19
This is a duplicate of #33

**Closed as completed by pobermei** 2020-12-10 11:19 UTC
